### ISSUE TITLE
Plugin fails to count words with accented characters (ö. ő. ü. ű, ú, ó...)

### ISSUE THREAD

**Issue by izdener** [benjypng/logseq-wordcount-plugin#21]
For example:
"törött" – broken – counts as 3
"őriz" – he/she/it guards – counts as 2
"húzza" – he/she/it pulls – counts as 2

**Comment by terezaondrus** [comment]
unfortunately, is does not work with Slovak language (characters) either, for example:
- stĺpcovitý graf = counts as 4 words instead of 2
- žaba = counts as 2 words instead of 1
- príbeh čo nás spája = counts as 8 words instead of 4

**Comment by benjypng** [comment]
Should be fixed in latest version. Ensure that the `forceWordCount` setting in the plugin is checked in order to count Cyrillic characters correctly.
