### ISSUE TITLE
Don't count Markdown-Link-URLs

### ISSUE THREAD

**Issue by theCalcaholic** [benjypng/logseq-wordcount-plugin#23]
If I have a Markdwon-Link like `[this](http://some-url)` in a block that has a word counter, the URL part should imo not increase the word count (because it is not displayed). However, in this example, both "http" and "some-url" seem to be counted individually, so the resulting count is 3.

Screenshots:

![image](https://github.com/hkgnp/logseq-wordcount-plugin/assets/6317548/e0e63dee-23c9-4509-9dbc-870fda841d1f)
![Screenshot from 2024-03-23 16-49-49](https://github.com/hkgnp/logseq-wordcount-plugin/assets/6317548/e0d79e24-5be9-456c-89e4-8279d626f375)

I suppose, even if the URL was to be counted, it should be counted as a single word, but that's technically a separate issue.

**Comment by benjypng** [comment]
Fixed in latest version.
