### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by owenbutler** [benjypng/logseq-wordcount-plugin#25]
### Context

I'm getting an error trying to install the plugin:

> [Error]<logseq-wordcount-plugin> :release-asset-not-found "null"]

Image:

![image](https://github.com/user-attachments/assets/27fbffde-ecce-4f74-b37f-6a76b5e6237e)

Logseq version 0.10.9, Windows 10.

**Comment by benjypng** [comment]
Sorry please try again.

**Comment by owenbutler** [comment]
That works, thanks 👍
